[[route]]
source = "/spin"
destination = "https://github.com/fermyon/spin"

[[route]]
source = "/hype"
destination = "https://www.fermyon.com/blog/how-to-think-about-wasm"

[[route]]
source = "/duckduckgo"
destination = "https://www.duckduckgo.com"
